export const API_URLS = {
  BASE_API_URL: import.meta.env.VITE_BASE_API_URL,
  ITEM_SERVICE_URL: import.meta.env.VITE_ITEM_SERVICE_URL,
  OUTFITS_SERVICE_URL: import.meta.env.VITE_OUTFITS_SERVICE_URL,
  OUTFITS_CATEGORIES_SERVICE_URL: import.meta.env.VITE_OUTFITS_CATEGORIES_SERVICE_URL,
};
